name: d:\BigData\.conda
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.11.14
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - beautifulsoup4==4.14.2
      - blinker==1.9.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - contourpy==1.3.3
      - curl-cffi==0.13.0
      - cycler==0.12.1
      - dask==2025.11.0
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozendict==2.4.7
      - fsspec==2025.10.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - locket==1.0.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - multitasking==0.0.12
      - namex==0.1.0
      - narwhals==2.12.0
      - numpy==2.3.5
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pandas==2.3.3
      - partd==1.4.2
      - peewee==3.18.3
      - pillow==12.0.0
      - platformdirs==4.5.0
      - plotly==6.5.0
      - protobuf==6.33.1
      - py4j==0.10.9.9
      - pyarrow==22.0.0
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyspark==4.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - six==1.17.0
      - soupsieve==2.8
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - toolz==1.1.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - yfinance==0.2.66
      - zipp==3.23.0
prefix: d:\BigData\.conda
